
 <div class="row">
 
 <div class="col-sm" >
<form action="" method="post" >
<input type="hidden"  name="profileId"  value="<?php echo $profile->id;?>">     

<div class="form-group">
 <label><h4>Name</h4></label>
 <input type="text" name="nickname" class="form-control" id="nickname" placeholder="Enter your name" value="<?php echo $event->name?>" required >
</div>
<div class="form-group">
 <label><h4>Date</h4></label>
 <input type="date" name="date" class="form-control" id="date" value="<?php echo $event->date?>" required>
</div>


<div class="form-group">
<label><h4>Detail</h4></label>
 <textarea type="text" name="data" class="form-control" id="data" placeholder="Max 200 Char" <?php echo $event->detail?> required  ><?php echo $event->detail?></textarea>
</div> 
<div class="form-group">
    <label>Picture</label>
    <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input"  >
          <label class="custom-file-label" >Choose file</label>
    </div>
  </div>
  <?php if($event->picture!=''){?>
            <div class="form-group text-center">  
                    <img style="width:100px; height:100px" src="<?php echo $this->url->getBaseUri().'public/img/'.$event->picture; ?>">
            </div>
        <?php }?>
 <div class="form-group">
 <button type="submit" class="btn btn-info">Submit</button>
<a href="<?php echo $this->url->getBaseUri();?>event" class="btn btn-warning">Back</a>
 </div>
</form>
 </div>
</div>