
 <div class="row">
 
    <div class="col-sm" >
  <form action="" method="post" enctype="multipart/form-data">
  <input type="hidden"  name="profileId"  value="<?php echo $profile->id;?>">     

  <div class="form-group">
    <label><h4>Name</h4></label>
    <input type="text" name="nickname" class="form-control" id="nickname" placeholder="Enter your name"  required >
  </div>
  <div class="form-group">
    <label><h4>Date</h4></label>
    <input type="date" name="date" class="form-control" id="date"  required>
  </div>
   
   
  <div class="form-group">
  <label><h4>Detail</h4></label>
    <input type="text" name="data" class="form-control" id="data" placeholder="Max 200 Char"  required  >
  </div> 
  <div class="form-group">
    <label><h4>Picture</h4></label>
    <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input"  >
          <label class="custom-file-label" >Choose file</label>
    </div>
  </div>
  <button type="submit" class="btn btn-info">Submit</button>
  <a href="<?php echo $this->url->getBaseUri();?>event" class="btn btn-warning">Back</a>

</form>
    </div>
  </div>