
 <div class="row">
    <div class="col-sm">     
    <img style="width:200px; height:200px" src="<?php echo $this->url->getBaseUri().'public/img/me.jpg'; ?>">
    </div>
<div class="col-sm">

  <div class="form-group" >
  <h1>SIRIWAT SUEBGINNORN</h1>
  </div>
  <div class="form-group">
 <h2>590610666</h2>
  </div>
  <div class="form-group">

  </div> 
    </div>
    <div class="col-sm">     
    </div>
  </div>